---
abstract: 'Plugin linking Dancer with Facebook::Graph'
author:
  - 'Michael Alan Dorman <mdorman@ironicdesign.com>'
build_requires:
  Dancer::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200003, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Facebook
requires:
  Dancer: 0
  Dancer::Plugin: 0
  Facebook::Graph: 0
version: 0.001
